server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: keycloak
                    uri: https://github.com/camiloestrada69/microserivicios-usuarios-vehiculos
                    search-paths: config-data
    application:
        name: config-service
